parameters:
#    armada_movie.example.class: Armada\MovieBundle\Example

services:
#    armada_movie.example:
#        class: %armada_movie.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
